### ISSUE TITLE
Source Code Request

### ISSUE THREAD

**Issue by ultranity** [bilateral-denoising-diffusion-model/bilateral-denoising-diffusion-model.github.io#1]
Is there any plan to release the Source Code?

**Comment by bilateral-denoising-diffusion-model** [comment]
Thanks for your interest! Yes, we plan to insert a link of public Github repo into the camera-ready paper (hopefully if this gets accepted) as soon as we receive the final decision.

**Comment by bilateral-denoising-diffusion-model** [comment]
FYI, our source code has been released at https://github.com/tencent-ailab/bddm
